name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:

  verify:
    env:
      INFO_LEVEL: ${{ vars.INFO_LEVEL }}
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        # [[ -f ${{ vars.FILE_TO_CHECK }} ]] ||
        # ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1 )
        [[ -f ${{ vars.FILE_TO_CHECK }} ]] &&
        ( echo "${{ vars.FILE_TO_CHECK }} file should be added to ${{ github.repository }} !" && exit 1 )    - run: echo "INFO_LEVEL=$INFO_LEVEL"
  do_something:
    defaults:
      run:
        shell: bash
        # working-directory: some
    runs-on: ubuntu-latest
    steps:
      - run: echo "runner os= $RUNNER_OS"
      - run: echo "runner os= ${{ runner.os }}"

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**.Cargo.lock') }}

    - name: simple step1
      run: |
        echo runner.os=  ${{ runner.os }}
        echo hash= ${{ hashFiles('**.Cargo.lock') }}
    - name: Build
      run: cargo build --verbose


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**.Cargo.lock') }}

    - name: simple step with multi line
      run: |
        echo simple step2
        echo with multi line
    - name: Run tests
      run: cargo test --verbose
